### ISSUE TITLE
OTP or OPT

### ISSUE THREAD

**Issue by julienchastang** [Unidata/online-python-training#105]
Having both Online Training Project (OTP) and Online Python Training (OPT) referenced in the same project is confusing.

**Comment by dopplershift** [comment]
That is pretty terrible. I think "Online Python Training" makes the most sense. @jwyoung?

**Comment by jwyoung** [comment]
As far as github, materials, or the Unidata website it should be Online Python Training. OTP is only the name for the funding increment.
