### ISSUE TITLE
Drop Python 3.4 from Travis

### ISSUE THREAD

**Issue by julienchastang** [Unidata/online-python-training#119]
Related to #118.

[Python 3.4 dependency in Travis](https://github.com/Unidata/online-python-training/blob/master/.travis.yml#L7) is, I believe, [reporting false negatives](https://travis-ci.org/Unidata/online-python-training/builds/399664222?utm_source=github_status&utm_medium=notification).

`3.5` works fine and the notebook in #118 runs without errors.

**Comment by dopplershift** [comment]
Probably should just replace it with 3.6

**Comment by julienchastang** [comment]
`3.6` it is.

**Comment by julienchastang** [comment]
closed by #120
