### ISSUE TITLE
Add a minimal readme

### ISSUE THREAD

**Issue by julienchastang** [Unidata/online-python-training#35]
Add a minimal readme

**Comment by lago8103** [comment]
Julien,
    I apologize but I do not know what you mean when you say to add a
minimal readme. May I please have some insight? Thanks! - Larissa

On Tue, Apr 26, 2016 at 5:39 PM, Julien Chastang notifications@github.com
wrote:

> Add a minimal readme
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Unidata/online-python-training/issues/35

## 

Larissa C. Gordon
Ecology and Evolutionary Biology Degree
       Atmospheric and Oceanic Science Minor
       Creative Writing, Fiction Studies Minor

University of Colorado, Boulder

**Comment by dopplershift** [comment]
If you go here: https://github.com/Unidata/unidata-python-workshop
The file `README.md` is displayed by default at the bottom of the page by default, giving some basic information about what's in the repository.

**Comment by julienchastang** [comment]
Done.
