### ISSUE TITLE
Reorganize after the Getting Started section

### ISSUE THREAD

**Issue by julienchastang** [Unidata/online-python-training#57]
@dopplershift 

I would suggest the following re-organization after the "Getting Started" section.
## Learning Basic Python
-   [Small intro written by us on what should be learned, e.g., flow control, data structures, etc.]
-   [Curated links, resources, books to learn basic Python]
### Intro
-   [Small intro written by us on what should be learned in the scientific Python arena and why, e.g., numpy, etc.]
### Books on Scientific Python
-   Decaria (also below in PyAOS section)
-   Python for Data Analysis (maybe?)
-   Others
### NumPy
-   [Curated links]
### Matplotlib
-   [Curated links]
### Intro
-   [Small intro written by us on what should be learned in the PyAOS arena and why, e.g., netcdf4-Python, etc.]
### Books on PyAOS
-   Johnny Lin's book
-   Decaria
### netCDF4-python
-   [Curated links]
### CartoPy
-   [Curated links]
### Siphon
-   [Curated links]
### Metpy
-   [Curated links]
## PyAOS Notebooks
-   [A well-maintained list of PyAOS notebooks according Mapes' suggestion and others]

**Comment by dopplershift** [comment]
Good topic of discussion for tomorrow's meeting.

**Comment by julienchastang** [comment]
Won't do. After discussion, we'll stick to our current high-level outline with a focus on meteorology for the Beginning Python Concepts sections.
